/**
 * Gradle file for all TeamCode dependencies
 *
 * Mainly to be used for custom enhancement libraries such as NextFTC, Pedro, etc.
 */

repositories {
    // Dairy maven repositories
    maven { url "https://repo.dairy.foundation/releases" }
    maven { url "https://repo.dairy.foundation/snapshots" }

    // NextFTC snapshots repository
    maven { url "https://central.sonatype.com/repository/maven-snapshots/" }
}

dependencies {
    implementation project(':FtcRobotController')

    implementation 'com.acmerobotics.slothboard:dashboard:0.2.4+0.5.1'

    implementation 'com.pedropathing:ftc:2.1.2'
    implementation 'com.pedropathing:telemetry:1.0.0'

    implementation 'dev.frozenmilk.dairy:MercurialFTC:2.0.0-beta9'
    implementation 'dev.frozenmilk.sinister:Sloth:0.2.4'

    implementation 'dev.nextftc.v2:robot:0.1.0'

    implementation 'gay.zharel.fateweaver:ftc:0.4.1'

    implementation 'page.j5155.AdvantageScope:lite:v26.0.0'
}
