//
// build.gradle in TeamCode
//
// Most of the definitions for building your module reside in a common, shared
// file 'build.common.gradle'. Being factored in this way makes it easier to
// integrate updates to the FTC into your code. If you really need to customize
// the build definitions, you can place those customizations in this file, but
// please think carefully as to whether such customizations are really necessary
// before doing so.


// Custom definitions may go here

// Include common definitions from above.
apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'
apply plugin: 'kotlin-android'

kotlin {
  jvmToolchain(8)
}

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

repositories {
    maven { url 'https://repo.dairy.foundation/releases' }
    maven { url 'https://repo.dairy.foundation/' }
    maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
}

dependencies {
    implementation project(':FtcRobotController')

    implementation 'org.psilynx.psikit:core:0.2.0-beta2'
    implementation 'org.psilynx.psikit:ftc:0.2.0-beta2'

    implementation 'dev.nextftc.v2:robot:0.0.2-SNAPSHOT'

    implementation 'com.pedropathing:ftc:2.1.2'
    implementation 'com.pedropathing:telemetry:1.0.0'
    implementation 'com.pedropathing:ivy:1.0.0'

    implementation "org.ejml:ejml-simple:0.41"
}
